# Generated by Django 4.0.5 on 2022-08-05 03:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='point_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='地点名')),
                ('katakana', models.CharField(max_length=31, verbose_name='カタカナ名')),
                ('address', models.CharField(max_length=31, verbose_name='住所')),
                ('ido', models.FloatField(verbose_name='緯度')),
                ('keido', models.FloatField(verbose_name='経度')),
                ('wgbt_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, max_length=25, null=True, size=6, verbose_name='24時間のwgbt')),
                ('time_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, max_length=25, null=True, size=6, verbose_name='時間リスト')),
            ],
            options={
                'verbose_name_plural': '地点名',
            },
        ),
    ]
